" $USERPROFILE/_vimrc

set runtimepath-=~/vimfiles
set runtimepath-=~/vimfiles/after
set runtimepath^=$USERPROFILE/.dotfiles/vim
set runtimepath+=$USERPROFILE/.dotfiles/vim/after

source $USERPROFILE/.dotfiles/vimrc
