#!bash

[[ $- != *i* ]] && return

. /usr/share/bash-completion/bash_completion

have() { command -v "$@" &>/dev/null; }

alias RM='/bin/rm'

rm() {
	local opts=() arg path nuke=() trash=()
	for arg; do
		if [[ $arg == -* ]]; then
			opts+=("$arg")
		elif case $(realpath -s "$arg") in
		# skip filesystems
		~/Private/*)		false;;
		~/fs/*)			false;;
		# skip system stuff
		~/lib/*)		false;;
		~/pkg/*)		false;;
		~/src/*)		false;;
		~/tmp*)			false;;
		# skip dotfiles and temp
		#~/.*)			false;;
		~/.local/share/Trash/*)	false;;
		*.tmp)			false;;
		.unison.*)		false;;
		# include everything else in $HOME
		~/*)			true;;
		# include removable drives
		/media/*)		true;;
		/run/media/*)		true;;
		# exclude everything else elsewhere
		*)			false;;
		esac; then
			trash+=("$arg")
		else
			nuke+=("$arg")
		fi
	done
	if (( ${#trash[@]} )); then
		trash "${opts[@]}" -- "${trash[@]}"
	fi &&
	if (( ${#nuke[@]} )); then
		command rm "${opts[@]}" -- "${nuke[@]}"
	fi
}

rpw() {
	local pw=$(tr -dc "A-Za-z0-9" < /dev/urandom | head -c "${1:-12}")
	echo "$pw"
	echo -n "$pw" | gclip
}

youtube-dl() {
	local cmd=()
	mountpoint -q /sys/fs/cgroup/systemd &&
	cmd+=(
		systemd-inhibit
		--who "youtube-dl"
		--what "sleep"
		--why "Downloading a video"
	)
	cmd+=(
		gnome-inhibit -A
		--who "youtube-dl"
		--what "suspend"
		--why "Downloading a video"
	)
	cmd+=(
		youtube-dl
		--console-title
		--continue
		"$@"
	)
	"${cmd[@]}"
}

_nolid_prompt() {
	if [[ -e "$XDG_RUNTIME_DIR/nolid.hold" ]]; then
		item_name_sfx=':[lid]'
	elif [[ -e "$XDG_RUNTIME_DIR/nolid.lock" ]]; then
		item_name_sfx=':lid'
	else
		item_name_sfx=''
	fi
	fmt_name_sfx='|38;5;238'
}

PROMPT_COMMAND+="; _nolid_prompt"
