#!bash

if [[ $TERM == @(ansi|cygwin) ]]; then
	. ~/.dotfiles/bash/prompt.sh
	fmts[a]='1;35'
	fmts[b]='1;35'
	fmts[c]='1;35'
	fmts[d]='35'
fi

if [[ $DISPLAY || $WAYLAND_DISPLAY ]]; then
	. ~/.dotfiles/bash/yank.sh
fi
