#!bash

umask 022

# paths

setpath() { local IFS=":" var="$1"; shift; export "$var=$*"; }

export PREFIX="$HOME/.local"

setpath PATH \
	"$HOME/bin"		\
	"$HOME/code/bin"	\
	"$PREFIX/bin"		\
	"$PATH"			\
	"/usr/local/sbin" 	\
	"/usr/sbin"		\
	"/sbin"			;

setpath PYTHONPATH \
	"$PREFIX/lib/python"	\
	"$HOME/code/lib/python"	;

setpath PERL5LIB \
	"$PREFIX/lib/perl5"	\
	"$HOME/code/lib/perl5"	;

# identity

export NAME='Mantas Mikulėnas'
export EMAIL="grawity@nullroute.eu.org"
export TZ="Europe/Vilnius"

# preferred programs

export PAGER="less"
export EDITOR="vim"
unset VISUAL
export BROWSER="web-browser"

# defaults

export ABSROOT="$HOME/pkg"
export _JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=on"
export NCURSES_NO_UTF8_ACS=1
