#!bash
[ "$DEBUG" ] && echo "++ environ"

setpath() { local IFS=: var=$1; shift; export "$var=$*"; }

umask 022

# paths

export PREFIX="$HOME/.local"

setpath PATH \
	"$HOME/.rbenv/shims"		\
	"$HOME/bin"			\
	"$HOME/code/obj/sys.$HOSTNAME"	\
	"$HOME/code/bin"		\
	"$HOME/.rbenv/bin"		\
	"$HOME/.cabal/bin"		\
	"$PREFIX/bin"			\
	"/usr/lib/ccache/bin"		\
	"/usr/lib/ccache"		\
	"$PATH"				\
	"/usr/local/sbin" 		\
	"/usr/sbin"			\
	"/sbin"				\
	"/opt/csw/bin"			\
	"$HOME/code/bin/fbin"		;

setpath PYTHONPATH \
	"$PREFIX/lib/python"		\
	"$HOME/code/lib/python"		;

setpath PERL5LIB \
	"$PREFIX/lib/perl5"		\
	"$HOME/code/lib/perl5"		;

export GNULIB_SRCDIR="$HOME/src/gnu/gnulib"

# identity

export NAME='Mantas Mikulėnas'
export EMAIL="grawity@nullroute.eu.org"
export TZ="Europe/Vilnius"

# preferred programs

export PAGER="less"
export EDITOR="vim"
unset VISUAL
export BROWSER="web-browser"

# libdefaults

export GTK_IM_MODULE="xim"
export _JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=on"
export NCURSES_NO_UTF8_ACS="1"
export QT_IM_MODULE="xim"

# appdefaults

export ABSROOT="$HOME/pkg"
export ACK_PAGER="$PAGER"
export LESS="e M q R F X z -3"
export LESSHISTFILE="$HOME/.cache/less.history"
export MAKEFLAGS="-j$(nproc)"
export MYSQL_HISTFILE="$HOME/.cache/mysql.history"
export PYTHONSTARTUP="$HOME/lib/dotfiles/pythonrc"

# local

if [ -e ~/lib/dotfiles/environ-$HOSTNAME ]; then
	. ~/lib/dotfiles/environ-$HOSTNAME
elif [ -e ~/.environ-$HOSTNAME ]; then
	. ~/.environ-$HOSTNAME
fi

# Perl

if [ "$LOCAL_PERL" = n ]; then
	export PERL_CPANM_OPT="--sudo"
else
	export PERL_MM_OPT="INSTALL_BASE='$PREFIX'"
	export PERL_MB_OPT="--install_base '$PREFIX'"
fi
