#!sh

setpath() { local IFS=: var=$1; shift; export "$var=$*"; }

umask 022

# paths

export PREFIX="$HOME/.local"

setpath PATH \
	"$HOME/bin"		\
	"$HOME/code/bin"	\
	"$HOME/.rbenv/shims"	\
	"$HOME/.rbenv/bin"	\
	"$HOME/.cabal/bin"	\
	"$PREFIX/bin"		\
	"/usr/lib/ccache/bin"	\
	"/usr/lib/ccache"	\
	"$PATH"			\
	"/usr/local/sbin" 	\
	"/usr/sbin"		\
	"/sbin"			;

setpath PYTHONPATH \
	"$PREFIX/lib/python"	\
	"$HOME/code/lib/python"	;

setpath PERL5LIB \
	"$PREFIX/lib/perl5"	\
	"$HOME/code/lib/perl5"	;

export GNULIB_SRCDIR="$HOME/src/gnu/gnulib"

# identity

export NAME='Mantas Mikulėnas'
export EMAIL="grawity@nullroute.eu.org"
export TZ="Europe/Vilnius"

# preferred programs

export PAGER="less"
export EDITOR="vim"
unset VISUAL
export BROWSER="web-browser"

# libdefaults

export GTK_IM_MODULE="xim"
export _JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=on"
export NCURSES_NO_UTF8_ACS="1"
export QT_IM_MODULE="xim"

# appdefaults

export ABSROOT="$HOME/pkg"
export ACK_PAGER="$PAGER"
export LESS="e M q R F X z -3"
export LESSHISTFILE=~/.cache/less.history
export MYSQL_HISTFILE="$HOME/.cache/mysql.history"
export PYTHONSTARTUP="$HOME/lib/dotfiles/pythonrc"

# local

if [ -e "$HOME/lib/dotfiles/environ-$HOSTNAME" ]; then
	. "$HOME/lib/dotfiles/environ-$HOSTNAME"
fi
