#!bash

unset ${!LC_*}

setpath PATH \
	~/lib/bup/bin		\
	~/lib/charybdis/bin	\
	"/usr/lib/ccache"	\
	"$PATH"			\
	"/usr/samba/bin"	\
	"/usr/samba/sbin"	\
	;

MPD_HOST=$(getnetrc -dsf '%p@%M' mpd@rain.nullroute.eu.org)
