#!/usr/bin/env bash
set -e

have() { command -v "$@" >/dev/null; }

link() {
	local target="$dir/${1%/}" link=$2
	if [ -e "$link" ]; then
		if [ -k "$link" ]; then
			echo "Ignoring sticky ${link/#$HOME/~}"
			return
		elif [ -h "$link" ]; then
			rm -f "$link"
		else
			trash "$link"
		fi
	fi
	sym -f "$target" "$link"
}

sym() { ~/code/bin/sym "$@"; }

trash() {
	local file
	for file; do
		if [ ! -e "$file" ]; then
			continue
		elif [ -k "$file" ]; then
			echo "Ignoring sticky ${file/#$HOME/~}"
			continue
		else
			if [ ! -d "$trash" ]; then
				mkdir -pm 0700 "$trash"
			fi
			echo "Backing up ${file/#$HOME/~} to ${trash/#$HOME/~}"
			mv "$file" "$trash"
		fi
	done
}

dir=$(dirname "$0")
trash=~/trash

mkdir -pm 0700 ~/.ssh

link bashrc	~/.bashrc
link gitconfig	~/.gitconfig
link gitignore	~/.gitignore
link inputrc	~/.inputrc
link profile	~/.profile
link vimrc	~/.vimrc
link vim/	~/.vim

trash ~/.cshrc
trash ~/.login
trash ~/.logout
trash ~/.shrc

"$dir/ssh-config.gen" -f

have bzr && {
	mkdir -p ~/.bazaar
	link bazaar/bazaar.conf ~/.bazaar/bazaar.conf
}

have gvim &&
	link gvimrc ~/.gvimrc

have makepkg &&
	link makepkg.conf ~/.makepkg.conf

trash	~/.bash_{login,profile,logout}

have irb &&
	link irbrc ~/.irbrc

have klist && {
	#link k5identity ~/.k5identity
	[[ -L ~/.k5identity ]] &&
		rm -f ~/.k5identity
}

have mail &&
	link mailrc ~/.mailrc

have msmtp && {
	link msmtprc ~/.msmtprc
	chmod 600 ~/.msmtprc
}

have mutt && {
	#link muttrc ~/.muttrc
	[[ ! -f ~/.muttrc ]] &&
		echo 'source "~/lib/dotfiles/muttrc"' > ~/.muttrc
}

have screen &&
	link screenrc ~/.screenrc

have tmux &&
	link tmux.conf ~/.tmux.conf

have xrdb && {
	link Xresources		~/.Xresources
	link XCompose		~/.XCompose
	link fonts.conf.xml	~/.fonts.conf
}

exit 0
