#!/usr/bin/env bash

log() { if [ -t 0 ]; then echo "$*"; fi; }

have() { command -v "$1" >/dev/null 2>&1; }

link() {
	local target=$dir/${1%/} link=${2:-$HOME/.$1}
	if [ ! -e "$target" ]; then
		log "Ignoring missing ${target/#$HOME/~}"
		return
	elif [ -e "$link" ]; then
		if [ -k "$link" ]; then
			log "Ignoring sticky ${link/#$HOME/~}"
			return
		elif [ -h "$link" ]; then
			rm -f "$link"
		else
			trash "$link"
		fi
	else
		local linkdir=${link%/*}
		if [ ! -d "$linkdir" ]; then
			mkdir -p "$linkdir"
		fi
	fi
	log "Linking ${link/#$HOME/~} to ${target/#$HOME/~}"
	sym -f "$target" "$link"
}

sym() { ~/code/bin/sym "$@"; }

trash() {
	local file
	for file; do
		if [ ! -e "$file" ]; then
			continue
		elif [ -k "$file" ]; then
			log "Ignoring sticky ${file/#$HOME/~}"
			continue
		else
			local hash=$(sha1sum "$file" | awk '{print $1}')
			if case $hash in
				79d58526d0e0bf4df4f01b383ed3f49c428aaa2a) true;;
				c7c4816f3cfa98298d7577af508ef63938426dd5) true;;
				dc216ac4a4c232815731979db6e494f315b507dd) true;;
				*) false;;
			esac; then
				rm -f "$file"
				continue
			fi
			if [ ! -d "$trash" ]; then
				mkdir -pm 0700 "$trash"
			fi
			echo "Backing up ${file/#$HOME/~} to ${trash/#$HOME/~}"
			mv "$file" "$trash"
		fi
	done
}

set -e

dir=$(dirname "$(readlink -f "$0")")
trash=~/Trash

cd "$dir"

trash ~/.{login,logout}
trash ~/.bash_{login,profile,logout}
trash ~/.{sh,csh}rc

link bashrc
link inputrc
link profile
link git ~/.config/git
if [ -h ~/.gitconfig ] || ! git config --global github.user >/dev/null 2>&1; then
	link git/config ~/.gitconfig
fi
if [ -h ~/.gitignore ]; then
	link git/ignore ~/.gitignore
fi
have msmtp && {
	link mail/msmtprc ~/.msmtprc
	chmod 600 ~/.msmtprc
}
have ssh && {
	ssh/generate
	link ssh/known_hosts
}
have tmux &&
	link tmux.conf

rm -f ~/.viminfo
link vimrc
link vim

test "$DISPLAY" && {
	have gvim &&
		link gvimrc
	have fc-cache && {
		link gui/fonts.conf.xml ~/.config/fontconfig/fonts.conf
	}
}

exit 0
