#!/usr/bin/env bash

for dir in ~/lib/code ~/etc/code ~/code; do
	if [[ -d $dir/bin ]]; then
		PATH=$dir/bin:$PATH
		break
	fi
done

. lib.bash || exit

progname='dotfiles/install'

trash() {
	local file
	for file; do
		if [ -k "$file" ]; then
			trace "ignoring sticky $file"
		elif [ -e "$file" ] || [ -h "$file" ]; then
			echo "backing up $file -> $trash"
			mkdir -pm 0700 "$trash"
			mv "$file" "$trash/old_${file##*/}"
		fi
	done
}

link() {
	local target=$dir/${1%/} link=${2:-$HOME/.$1}
	if [ ! -e "$target" ]; then
		err "link target is missing: $link -> $target"
		return
	elif [ -e "$link" ]; then
		if [ -k "$link" ]; then
			trace "ignoring sticky $link"
			return
		elif [ -h "$link" ]; then
			rm -f "$link"
		else
			trash "$link"
		fi
	else
		local linkdir=${link%/*}
		if [ ! -d "$linkdir" ]; then
			mkdir -p "$linkdir"
		fi
	fi
	trace "linking $link -> $target"
	sym -f "$target" "$link"
}

if [[ -t 0 ]]; then
	VERBOSE=1
fi

dir=$(dirname "$(sym -R "$0")")
trash=~/tmp

cd "$dir"

trash ~/.{login,logout}
trash ~/.bash_{login,profile,logout}
trash ~/.{sh,csh}rc
rm -f ~/.viminfo

link bashrc
link inputrc
link profile
link git ~/.config/git
link vim ~/.vim
link vim ~/.config/nvim

if [ -d ~/.config/htop ]; then
	rm -f ~/.htoprc
	if ! grep -qs "^#" ~/.config/htop/htoprc; then
		cp htoprc ~/.config/htop/htoprc
	fi
elif [ ! -e ~/.htoprc ]; then
	mkdir -p ~/.config/htop
	cp htoprc ~/.config/htop/htoprc
fi

(umask 077; touch ~/.config/git/credentials)

if have makepkg; then
	link pacman/makepkg.conf ~/.config/pacman/makepkg.conf
fi

if have msmtp; then
	link mail/msmtprc ~/.msmtprc
	chmod 600 ~/.msmtprc
fi

if have radare2; then
	link radare2rc ~/.config/radare2/radare2rc
fi

if have ssh; then
	trace "updating $HOME/.ssh/config"
	ssh/generate
	link ssh/known_hosts
fi

if have tmux; then
	link tmux.conf
fi

if [ "$DISPLAY" ]; then
	link gui/XCompose ~/.XCompose

	if ! [ -d ~/.local/share/themes/Adwaita ]; then
		mkdir -p ~/.local/share/themes/Adwaita
		ln -s /usr/share/themes/Clearlooks/gtk-2.0 ~/.local/share/themes/Adwaita/
	fi

	[ -d ~/.thumbnails ] || sym -f ~/.cache/thumbnails   ~/.thumbnails
	[ -d ~/.fonts ]      || sym -f ~/.local/share/fonts  ~/.fonts
	[ -d ~/.themes ]     || sym -f ~/.local/share/themes ~/.themes

	if have fc-cache && [ ! -d ~/.config/fontconfig ]; then
		link gui/fontconfig ~/.config/fontconfig
	fi

	if have openbox; then
		link gui/openbox/autostart ~/.config/openbox/autostart
		link gui/openbox/rc.xml    ~/.config/openbox/rc.xml
	fi

	if [ ! -f ~/.config/user-dirs.dirs ]; then
		cp gui/user-dirs.dirs ~/.config/user-dirs.dirs
	fi
fi

badfiles=( ~/.*_history ~/.lesshst ~/.rnd
           ~/.config ~/.cache ~/.gnupg ~/.local/share )

for f in "${badfiles[@]}"; do
	if [ -h "$f" ]; then
		continue
	elif [ -e "$f" ] && [ ! -O "$f" ]; then
		trace "file '$f' not owned by me, replacing"
		trash "$f"
		(umask 077; touch "$f")
	elif [ -d "$f" ] && [ ! -O "$f" ]; then
		trace "dir '$f' not owned by me, replacing"
		trash "$f"
		(umask 077; mkdir "$f")
	fi
done

exit 0
