#!bash

confirm() {
	local msg=$1 ans=
	if [ "$DISPLAY" ]; then
		zenity --question \
			--title "nullroute login" \
			--text "$1"
	else
		read -ep $'\001\e[1;36m\002(?)\001\e[m\002'" $msg " \
			-t 10 ans && [[ $ans == [Yy] ]]
	fi
}

if ! klist -s; then
	confirm "No Kerberos tickets found. Login anyway?" || exit
fi

if ! [ -d ~/rain ]; then
	confirm "Home directory not mounted. Login anyway?" || exit
fi
