#!bash

# Preferred programs

export BROWSER="elinks"

setpath PATH \
	"/usr/lib/ccache/bin"				\
	"$(ruby -rubygems -e 'puts Gem.user_dir')/bin"	\
	"$PATH"						;

# Program defaults

export MAKEFLAGS="-j5"
export NWCLIENT_DEFAULT_USER="$USER"

export MPD_HOST="$(<~/.config/mpd/password)@$XDG_RUNTIME_DIR/mpd.control"

# Locations

export ACCDB="/run/media/$USER/grawpqi/private/accounts.db.txt"
export CLUENET_DIR="$HOME/src/cluenet"
export GNULIB_SRCDIR="$HOME/src/gnu/gnulib"

if [ -z "$KRB5CCNAME" ]; then
	if [ "$XDG_RUNTIME_DIR" ] && [ -d "$XDG_RUNTIME_DIR" ]; then
		mkdir -p "$XDG_RUNTIME_DIR/krb5cc"
		export KRB5CCNAME="DIR:$XDG_RUNTIME_DIR/krb5cc"
	elif [ -O "/tmp/krb5cc_$UID.d" ] && [ -d "/tmp/krb5cc_$UID.d" ]; then
		export KRB5CCNAME="DIR:/tmp/krb5cc_$UID.d"
	elif mkdir -m 0700 "/tmp/krb5cc_$UID.d" 2>/dev/null; then
		export KRB5CCNAME="DIR:/tmp/krb5cc_$UID.d"
	fi
fi

# Library settings

export GTK_IM_MODULE="xim"
export QT_IM_MODULE="xim"

# Etc.

#export LD_PRELOAD='/usr/$LIB/libv4l/v4l1compat.so'
#export WINEDLLOVERRIDES="winemenubuilder.exe=d"

if [ ! -e "$XDG_RUNTIME_DIR/gvfs" ]; then
	mountpoint -q "$XDG_RUNTIME_DIR/gvfs" &&
	fusermount -u "$XDG_RUNTIME_DIR/gvfs"
fi >/dev/null 2>&1

if ! mountpoint -q ~/Private; then
	if [ "$DISPLAY" ]; then
		spawn ecryptfs-mount-x11
	elif [ -t 1 ]; then
		echo "Warning: ~/Private not mounted" >&2
	fi
fi

#spawn pkinit

acpi
