#!sh

if [ -d "$XDG_RUNTIME_DIR" ]; then
	ln -nsf "/run/media/$USER" "$XDG_RUNTIME_DIR/media"
	ln -nsf "$XDG_RUNTIME_DIR" "$HOME/.run"
fi

if [ ! -e "$XDG_RUNTIME_DIR/gvfs" ]; then
	mountpoint -q "$XDG_RUNTIME_DIR/gvfs" &&
	fusermount -u "$XDG_RUNTIME_DIR/gvfs"
fi >/dev/null 2>&1

if ! mountpoint -q ~/Private; then
	if [ "$DISPLAY" ]; then
		spawn ecryptfs-mount-x11
	elif [ -t 1 ]; then
		echo -e "\e[1mWarning: ~/Private not mounted\e[m" >&2
	fi
fi

spawn -L mpd

spawn -L mpdscribble

if [ "$(tty)" = "/dev/tty1" ]; then
	exec sx
fi

acpi
