#!/usr/bin/env bash
wmiir read /ctl > /dev/null || exit 1

if [ "$1" ]; then
	wmiir xwrite /event "Debug $*"
	exit
fi

tail -fn0 ~/.wmii/debug.log & tailpid=$!
trap "kill $tailpid; exit" INT TERM QUIT HUP EXIT

# No prompt as it would show up before async output
wmiir xwrite /event "Debug poke"
while read -e -r -p "" cmd; do
	[ "$cmd" ] || continue
	wmiir xwrite /event "Debug $cmd"
done
kill $tailpid
