#!/usr/bin/env bash

#{ inotifywait -r -m -q -e close_write ~/.themes/wh-mod/openbox-3/themerc \
#  | while read event; do
#	openbox --reconfigure
#  done; } &

if [[ $HOSTNAME == fujitsu ]]; then
	xset s $[5*60]

	xss-lock ~/bin/lock-session auto &

	xsettingsd &

	#stalonetray &
	xfce4-panel &

	nm-applet &

	upower-monitor &

	start-dropbox &
fi

gnome-terminal &
