#!/usr/bin/env zsh

# terminal setup
# https://github.com/vodik/dotfiles/blob/master/shell/zsh/bindkeys.zsh

autoload zsh/terminfo

# keybindings

bindkey -e

bindkey '\e[H' beginning-of-line	# Home
bindkey '\e[F' end-of-line		# End
bindkey '\eOH' beginning-of-line	# Home
bindkey '\eOF' end-of-line		# End
bindkey '\e[3~' delete-char		# Del
bindkey '\e[5~' beep			# Page Up
bindkey '\e[6~' beep			# Page Down
bindkey '\eOQ' describe-key-briefly	# F2

# macros

bindkey '\e:' execute-named-cmd
