#!/bin/bash
wmiir read /ctl > /dev/null || exit 1

tail -Fn0 ~/.wmii-hg/debug.log & tailpid=$!
trap "kill $tailpid; exit" INT TERM QUIT HUP EXIT

wmiir xwrite /event "eval poke"
while read -er cmd; do
	[ "$cmd" ] || continue
	wmiir xwrite /event "eval $cmd"
done
kill $tailpid
