#!/bin/bash
wmiir read /ctl > /dev/null || exit 1
wmiir xwrite /event "eval poke"

tail -fn1 ~/.wmii-hg/debug.log & tailpid=$!
trap "kill $tailpid; exit" INT TERM QUIT HUP EXIT

while read -er cmd; do
	[ "$cmd" ] || continue
	wmiir xwrite /event "eval $cmd"
done
kill $tailpid
